### ISSUE TITLE
Xquartz Mac OS Big Sur

### ISSUE THREAD

**Issue by ingohoffmann2** [SASfit/SASfit#5] opened 2021-03-11 15:23 UTC
Not so much of a bug in sasfit but potentially useful as reference nevertheless:
As of Mac OS Big Sur and using Xquartz 2.7.11, Xquartz needs to be started manually before starting sasfit. Otherwise it will produce an error message:

couldn't connect to display ":0"

**Comment by ibressler** [comment] 2021-03-11 16:12
Thank you for this feedback, it's very helpful info!
(Especially for those you come across this issue too.)

Perhaps, we can fix this in future releases of SASfit.

Am 11.03.21 um 16:23 schrieb ingohoffmann2:

**Comment by ibressler** [comment] 2022-04-07 11:01
Tested on macOS 11.6.5 with xquartz 2.7.11 installed by brew, I can't reproduce this.
SASfit just starts and xquartz runs along with it - it's very likely to be a local site-specific issue with xquartz installation if this problem persists.
I am closing this issue for now. Please reopen if the problem comes up again, thanks!

**Closed** 2022-04-07 11:01 UTC
